### ISSUE TITLE
Would like to have the reference paper used in the code

### ISSUE THREAD

**Issue by siddharthumakarthikeyan** [Daveorr/Omni-directional-Robot-Model#1]
Hello,
Thanks for sharing the code. It would be greatly helpful if you could share the reference paper which you had mentioned in the code (Equation numbers are mentioned in the code) so that it will be quite easy to follow. Thanks

**Comment by Daveorr** [comment]
https://drive.google.com/file/d/1ZcCbBSR3Ej5LelZVrkgjPPdYrF3NjeZ2/view?usp=sharing
